import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../dist/server/index.js';
test('60 seconds of active pulses earns one litre; bursts, replays and idle time earn nothing',async()=>{
 const env=environment(),real=Date.now;let time=1800000000000;Date.now=()=>time;
 try{await create(env,'alice');const start=await (await call(env,'/api/gas/start','alice',{})).json();let seq=0;
 for(let i=0;i<20;i++){time+=3000;const d=await (await call(env,'/api/gas/pulse','alice',{session:start.session,sequence:++seq})).json();assert.equal(d.gas.progress,(i===19?0:(i+1)*3000))}
 let gas=(await (await call(env,'/api/account')).json()).gas;assert.equal(gas.free,1);assert.equal(gas.paid,0);
 await call(env,'/api/gas/pulse','alice',{session:start.session,sequence:seq});assert.equal((await (await call(env,'/api/account')).json()).gas.free,1);
 for(let i=0;i<20;i++)await call(env,'/api/gas/pulse','alice',{session:start.session,sequence:++seq});assert.equal((await (await call(env,'/api/account')).json()).gas.progress,0);
 time+=60000;await call(env,'/api/gas/pulse','alice',{session:start.session,sequence:++seq});gas=(await (await call(env,'/api/account')).json()).gas;assert.equal(gas.progress,0);assert.ok(gas.free<1);
 assert.equal((await call(env,'/api/gas/pulse','bob',{session:start.session,sequence:++seq})).status,400);
 }finally{Date.now=real;env.sql.close()}
});
test('free burns 24 L/day, paid burns 1 L/day; balances never become negative and ranking follows sum',async()=>{
 const env=environment(),real=Date.now;let time=1800000000000;Date.now=()=>time;
 try{const a=await create(env,'alice'),b=await create(env,'bob');await env.DB.prepare('INSERT INTO gas_tanks (profile,free,paid,updated) VALUES (?,?,?,?)').bind(a.id,24*86400000,2*86400000,time).run();await env.DB.prepare('INSERT INTO gas_tanks (profile,free,paid,updated) VALUES (?,?,?,?)').bind(b.id,0,25.5*86400000,time).run();let board=(await (await call(env,'/api/profiles')).json()).profiles;assert.equal(board[0].id,a.id);
 time+=3600000;let g=(await (await call(env,'/api/account')).json()).gas;assert.equal(g.free,23);assert.ok(Math.abs(g.paid-(2-1/24))<1e-10);board=(await (await call(env,'/api/profiles')).json()).profiles;assert.equal(board[0].id,b.id);
 time+=23*3600000;g=(await (await call(env,'/api/account')).json()).gas;assert.deepEqual({free:g.free,paid:g.paid,total:g.total},{free:0,paid:1,total:1});
 time+=86400000;g=(await (await call(env,'/api/account')).json()).gas;assert.equal(g.total,0);assert.equal((await (await call(env,'/api/account')).json()).rank,null);
 }finally{Date.now=real;env.sql.close()}
});
test('pump sessions invalidate other tabs and concurrent pulses cannot duplicate earned gas',async()=>{const env=environment(),real=Date.now;let time=1800000000000;Date.now=()=>time;try{const p=await create(env,'alice');const a=await (await call(env,'/api/gas/start','alice',{})).json(),b=await (await call(env,'/api/gas/start','alice',{})).json();assert.equal((await call(env,'/api/gas/pulse','alice',{session:a.session,sequence:1})).status,409);await env.DB.prepare('UPDATE gas_tanks SET progress=57000 WHERE profile=?').bind(p.id).run();time+=3000;await Promise.all([call(env,'/api/gas/pulse','alice',{session:b.session,sequence:1}),call(env,'/api/gas/pulse','alice',{session:b.session,sequence:1})]);assert.equal((await (await call(env,'/api/account')).json()).gas.free,1)}finally{Date.now=real;env.sql.close()}});
test('paid gas costs exactly $1/L and confirmed payment credits only once',async()=>{
 const env=environment();env.CRYPTO_PAYMENTS_ENABLED='true';env.NOWPAYMENTS_API_KEY='test-key';env.PURCHASE_TERMS_URL='https://linkdid.test/terms';await create(env,'alice');const original=globalThis.fetch;let order,status='partially_paid',posted;
 globalThis.fetch=async(url,opts)=>{if(url.endsWith('/currencies'))return Response.json({currencies:['btc']});if(opts.method==='POST'){posted=JSON.parse(opts.body);order=posted.order_id;return Response.json({payment_id:123,pay_address:'test',pay_amount:.001,pay_currency:'btc'})}return Response.json({payment_id:123,order_id:order,price_amount:3,price_currency:'usd',pay_currency:'btc',payment_status:status,pay_amount:.001,actually_paid:.001})};
 try{const id=crypto.randomUUID(),body={id,litres:3,amount:1,currency:'btc',accepted:true};assert.equal((await call(env,'/api/crypto/orders','alice',body)).status,200);assert.equal(posted.price_amount,3);await call(env,'/api/crypto/orders/'+id+'/check','alice',{});assert.equal((await (await call(env,'/api/account')).json()).gas.paid,0);status='finished';env.sql.prepare('UPDATE orders SET checked=0').run();assert.equal((await call(env,'/api/crypto/orders/'+id+'/check','alice',{})).status,200);await call(env,'/api/crypto/orders/'+id+'/check','alice',{});const g=(await (await call(env,'/api/account')).json()).gas;assert.ok(g.paid>2.99&&g.paid<=3);assert.equal(g.free,0);assert.equal((await call(env,'/api/crypto/orders/'+id+'/receipt','bob')).status,404);assert.equal(env.sql.prepare('SELECT COUNT(*) n FROM paid_bids').get().n,0)}finally{globalThis.fetch=original;env.sql.close()}
});
test('legacy identity still resolves to the existing profile in gas mode',async()=>{const env=environment();const email='legacy@example.test',base={'x-dispatched-app':'site---configure-your-sites-project','oai-authenticated-user-email':email};const invoke=(path,headers,body)=>worker.fetch(new Request('https://linkdid.test'+path,{method:body?'POST':'GET',headers:{...headers,...(body?{origin:'https://linkdid.test','content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),env);await invoke('/api/profile',base,{name:'Legacy',headline:'Designer',url:'https://www.linkedin.com/in/legacy',category:'Design'});const current={...base,'oai-authenticated-user-id':'new-stable-id'};assert.equal((await (await invoke('/api/account',current)).json()).profile.name,'Legacy');assert.equal((await invoke('/api/gas/start',current,{})).status,200);env.sql.close()});
test('gas routes enforce ownership and retire claim bidding; checkout remains gated',async()=>{const env=environment();assert.equal((await call(env,'/api/gas/start',null,{})).status,401);assert.equal((await call(env,'/api/gas/start','alice',{})).status,400);assert.equal((await call(env,'/api/claim','alice',{})).status,410);assert.equal((await call(env,'/api/crypto/orders','alice',{})).status,503);assert.equal((await (await call(env,'/api/me')).json()).mode,'gas');env.sql.close()});
function environment(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const name of ['0000_spicy_mephistopheles.sql','0001_wakeful_tigra.sql','0002_big_strong_guy.sql','0003_great_puma.sql'])sql.exec(readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8'));const db={prepare(query){let args=[];return {bind(...a){args=a;return this},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return sql.prepare(query).run(...args)}}},async batch(statements){sql.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};const files=new Map();return {DB:db,BUCKET:{async put(key,data,meta){files.set(key,{body:data,httpMetadata:meta.httpMetadata})},async get(key){return files.get(key)}},sql};}
async function call(env,path,who='alice',body,origin='https://linkdid.test'){return worker.fetch(new Request('https://linkdid.test'+path,{method:body===undefined?'GET':'POST',headers:{...(who?{'oai-authenticated-user-id':who,'oai-authenticated-user-email':who+'@example.test'}:{}),...(body!==undefined?{'content-type':'application/json',origin}: {})},body:body===undefined?undefined:JSON.stringify(body)}),env)}
async function create(env,who){const r=await call(env,'/api/profile',who,{name:who,headline:'Product designer',url:'https://www.linkedin.com/in/'+who,category:'Design',location:'London'});assert.equal(r.status,200);return (await (await call(env,'/api/account',who)).json()).profile;}
test('hold sessions save release progress, exclude pauses, and stop server-side at one litre',async()=>{const env=environment(),real=Date.now;let time=1800000000000;Date.now=()=>time;try{await create(env,'alice');let s=await (await call(env,'/api/gas/start','alice',{})).json();time+=500;let d=await (await call(env,'/api/gas/pulse','alice',{session:s.session,sequence:1,heldMs:500,stop:true})).json();assert.equal(d.gas.progress,500);assert.equal(d.stopped,true);time+=100000;d=await (await call(env,'/api/gas/pulse','alice',{session:s.session,sequence:2,heldMs:3000})).json();assert.equal(d.gas.progress,500);s=await (await call(env,'/api/gas/start','alice',{})).json();for(let seq=1;seq<=60;seq++){const ms=seq===60?500:1000;time+=ms;d=await (await call(env,'/api/gas/pulse','alice',{session:s.session,sequence:seq,heldMs:ms})).json()}assert.equal(d.complete,true);assert.equal(d.gas.free,1);assert.equal(d.gas.progress,0);time+=3000;d=await (await call(env,'/api/gas/pulse','alice',{session:s.session,sequence:61,heldMs:3000})).json();assert.equal(d.complete,true);assert.equal(d.earned,0);assert.equal(d.gas.progress,0);assert.ok(d.gas.free<=1);const image=await call(env,'/pump-machine.webp');assert.equal(image.headers.get('content-type'),'image/webp');const data=Buffer.from(await image.arrayBuffer());assert.equal(data.toString('ascii',0,4),'RIFF')}finally{Date.now=real;env.sql.close()}});
test('expanded categories save and public directory stats contain only aggregate metrics',async()=>{const env=environment();try{for(const category of ['SEO','Agents','Real Estate','Analytics','Developer']){const r=await call(env,'/api/profile','alice',{name:'Alice',headline:'Professional',url:'https://www.linkedin.com/in/alice',category});assert.equal(r.status,200);assert.equal((await (await call(env,'/api/account')).json()).profile.category,category)}const d=await (await call(env,'/api/profiles',null)).json();assert.deepEqual(d.stats,{profiles:1,clicks:0,views:0});assert.equal(JSON.stringify(d).includes('owner'),false)}finally{env.sql.close()}});
test('anonymous writes and cross-origin writes are rejected',async()=>{const env=environment();assert.equal((await call(env,'/api/profile',null,{})).status,401);assert.equal((await call(env,'/api/profile','alice',{},'https://attacker.test')).status,403);env.sql.close()});
test('live email-only dispatcher identity can save and reload an owned profile',async()=>{const env=environment();const email='owner@example.test';const headers={'oai-authenticated-user-email':email,'x-dispatched-app':'site---configure-your-sites-project'};const get=path=>worker.fetch(new Request('https://linkdid.test'+path,{headers}),env);assert.equal((await (await get('/api/me')).json()).user.email,email);const save=await worker.fetch(new Request('https://linkdid.test/api/profile',{method:'POST',headers:{...headers,origin:'https://linkdid.test','content-type':'application/json'},body:JSON.stringify({name:'Owner',headline:'Designer',url:'https://www.linkedin.com/in/owner',category:'Design'})}),env);assert.equal(save.status,200);assert.equal((await (await get('/api/account')).json()).profile.name,'Owner');const anonymousEmail=await worker.fetch(new Request('https://linkdid.test/api/account',{headers:{'oai-authenticated-user-email':email}}),env);assert.equal(anonymousEmail.status,401);const other=await worker.fetch(new Request('https://linkdid.test/api/account',{headers:{...headers,'oai-authenticated-user-email':'other@example.test'}}),env);assert.equal((await other.json()).profile,null);env.sql.close()});
test('metrics deduplicate signed-in visitors and exclude owner and anonymous views',async()=>{const env=environment();const a=await create(env,'alice');await call(env,'/api/view/'+a.id,'alice',{});await call(env,'/api/view/'+a.id,null,{});await call(env,'/api/view/'+a.id,'bob',{});await call(env,'/api/view/'+a.id,'bob',{});const go=await call(env,'/go/'+a.id,'bob');assert.equal(go.status,302);assert.equal(go.headers.get('location'),a.url);await call(env,'/go/'+a.id,'bob');const account=await (await call(env,'/api/account')).json();assert.deepEqual(account.stats,{views:1,clicks:1});env.sql.close()});
test('photo upload requires a saved owned profile and rejects non-images',async()=>{const env=environment();const a=await create(env,'alice');const send=(data,who)=>worker.fetch(new Request('https://linkdid.test/api/photo',{method:'POST',headers:{origin:'https://linkdid.test','oai-authenticated-user-id':who,'content-type':'image/png'},body:data}),env);assert.equal((await send('not really an image','alice')).status,400);const png=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0]);assert.equal((await send(png,'bob')).status,400);assert.equal((await send(png,'alice')).status,200);const account=await (await call(env,'/api/account')).json();assert.match(account.profile.photo,/^\/photos\//);const photo=await call(env,'/photos/'+a.id);assert.equal(photo.headers.get('content-type'),'image/png');env.sql.close()});
