import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const HoldPump=runInNewContext(readFileSync(new URL('../dist/hold-pump.js',import.meta.url),'utf8').split('let holdPump=null')[0]+'\nHoldPump');
function setup(){let time=0,progress=0,litres=0,sequence=0,session=0,stopped=false;const sounds=[],requests=[];
 const request=async(path,b)=>{requests.push({path,...b});if(path.endsWith('start')){session++;sequence=0;stopped=false;return {session:String(session),gas:{progress,sequence},serverNow:time}}if(!stopped){progress+=b.heldMs;sequence=b.sequence;if(progress>=60000){progress=0;litres++;stopped=true}else if(b.stop)stopped=true}return {gas:{progress,sequence},stopped,complete:stopped&&progress===0&&litres>0,serverNow:time}};
 const pump=new HoldPump({request,clock:()=>time,sound:x=>sounds.push(x)});return {pump,sounds,requests,advance:ms=>time+=ms,progress:()=>progress,litres:()=>litres,request};
}
test('holding for 60 seconds awards exactly one litre and requires a new gesture',async()=>{const s=setup();await s.pump.press();for(let i=0;i<60;i++){s.advance(1000);await s.pump.heartbeat()}assert.equal(s.litres(),1);assert.equal(s.pump.held,false);assert.equal(s.pump.complete,true);assert.equal(s.sounds.at(-1),false);for(let i=0;i<60;i++){s.advance(1000);await s.pump.heartbeat()}await s.pump.press();assert.equal(s.litres(),1);await s.pump.release();await s.pump.press();for(let i=0;i<60;i++){s.advance(1000);await s.pump.heartbeat()}assert.equal(s.litres(),2)});
test('release stops sound immediately, saves fractional progress, and excludes idle time',async()=>{const s=setup();await s.pump.press();s.advance(1250);await s.pump.release();assert.equal(s.progress(),1250);assert.equal(s.sounds.at(-1),false);s.advance(3600000);await s.pump.heartbeat();assert.equal(s.progress(),1250);assert.equal(s.litres(),0);await s.pump.press();s.advance(1000);await s.pump.heartbeat();assert.equal(s.progress(),2250)});
test('release during an in-flight pulse flushes only the held tail and never resumes sound',async()=>{const s=setup();await s.pump.press();let resolve;const original=s.pump.request;s.pump.request=(path,b)=>path.endsWith('pulse')&&b.sequence===1?new Promise(r=>{resolve=async()=>r(await original(path,b))}):original(path,b);s.advance(1000);const pending=s.pump.heartbeat();s.advance(250);await s.pump.release();assert.equal(s.pump.held,false);assert.equal(s.sounds.at(-1),false);await resolve();await pending;assert.equal(s.progress(),1250);assert.equal(s.pump.session,null);assert.equal(s.sounds.at(-1),false);assert.equal(s.requests.at(-1).stop,true)});
test('releasing while connecting cannot leave the pump earning in the background',async()=>{const s=setup();let resolve;const original=s.pump.request;s.pump.request=(path,b)=>path.endsWith('start')?new Promise(r=>{resolve=async()=>r(await original(path,b))}):original(path,b);const pending=s.pump.press();s.advance(500);await s.pump.release();await resolve();await pending;assert.equal(s.progress(),0);assert.equal(s.pump.session,null);assert.equal(s.pump.held,false);assert.equal(s.sounds.at(-1),false)});
test('gas session waits for the nozzle to plug in and cancelling motion starts no session',async()=>{const s=setup();let finish;s.pump.connect=()=>new Promise(r=>finish=r);const pending=s.pump.press();s.advance(700);await s.pump.heartbeat();assert.equal(s.requests.length,0);await s.pump.release();finish(false);await pending;assert.equal(s.requests.length,0);assert.equal(s.pump.busy,false);const retry=s.pump.press();finish(true);await retry;assert.equal(s.requests.length,1);s.advance(1000);await s.pump.heartbeat();assert.equal(s.progress(),1000)});
