import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const NozzleMotion=runInNewContext(readFileSync(new URL('../dist/nozzle-motion.js',import.meta.url),'utf8').split('let nozzleMotion=null')[0]+'\nNozzleMotion');
test('attendant connects before earning can start and reverses to exactly the seated nozzle',async()=>{let time=0,parked=0;const clicks=[],frames=[],m=new NozzleMotion({clock:()=>time,couple:x=>clicks.push(x),park:()=>parked++,update:p=>frames.push(p.frame)});const ready=m.connect();time=750;m.frame();assert.equal(m.phase,'connecting');time=1650;m.frame();assert.equal(await ready,true);assert.equal(m.phase,'connected');assert.equal(m.position,11);m.stop();assert.equal(m.phase,'unplugging');time+=1500;m.frame();assert.equal(m.phase,'securing');assert.equal(parked,0);time+=150;m.frame();assert.equal(m.phase,'docked');assert.equal(frames.at(-1),frames[0]);assert.equal(parked,1);m.frame();m.stop();assert.equal(parked,1);assert.deepEqual(clicks,[true,false])});
test('release while attendant connects cancels the promise and a new hold continues from current pose',async()=>{let time=0;const m=new NozzleMotion({clock:()=>time});const first=m.connect();time=600;m.frame();m.stop();assert.equal(await first,false);time=750;m.frame();const position=m.position;const second=m.connect();assert.equal(m.position,position);time+=1650;m.frame();assert.equal(await second,true);assert.equal(m.phase,'connected')});
test('reduced motion retains docked and inserted poses with the same completion callbacks',async()=>{let time=0,parked=0;const m=new NozzleMotion({clock:()=>time,reduced:true,park:()=>parked++});const ready=m.connect();m.frame();assert.equal(await ready,true);assert.equal(m.position,11);m.stop();m.frame();assert.equal(m.position,0);assert.equal(parked,1)});

test('immediate release and re-press while still inserted resolves without a stalled pump',async()=>{let time=0;const m=new NozzleMotion({clock:()=>time});const first=m.connect();time=1650;m.frame();await first;m.stop();const second=m.connect();assert.equal(await second,true);assert.equal(m.phase,'connected')});
