import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const source=readFileSync(new URL('../dist/hold-pump.js',import.meta.url),'utf8').split('class PumpAudio {')[1].split('function renderHoldState')[0];
function fixture(){const spoken=[],settings=new Map(),doc={visibilityState:'visible',hasFocus:()=>true};let cancelled=0;const window={SpeechSynthesisUtterance:class{constructor(text){this.text=text}},speechSynthesis:{cancel(){cancelled++},speak(u){spoken.push(u)},getVoices:()=>[{name:'Samantha',lang:'en-US'}]}};const Audio=runInNewContext('class PumpAudio {'+source+'\nPumpAudio',{window,document:doc,localStorage:{getItem:k=>settings.get(k),setItem:(k,v)=>settings.set(k,v)},holdPump:null,$:()=>null});return{audio:new Audio(),spoken,doc,settings,window,cancels:()=>cancelled}}
test('voice is spoken only when enabled and visible; muting cancels ongoing narration',()=>{const f=fixture();f.audio.speak('Filling started.');assert.equal(f.spoken[0].text,'Filling started.');assert.equal(f.audio.speaking,true);f.audio.toggle();assert.equal(f.audio.muted,true);assert.equal(f.audio.speaking,false);f.audio.speak('Nozzle secured.');assert.equal(f.spoken.length,1);f.audio.toggle();f.doc.visibilityState='hidden';f.audio.speak('Filling started.');assert.equal(f.spoken.length,1);assert.ok(f.cancels()>=2)});
test('stale speech completion cannot interrupt a newer cue and voice preference persists',()=>{const f=fixture();f.audio.speak('First');f.audio.speak('Second');f.spoken[0].onend();assert.equal(f.audio.speaking,true);f.spoken[1].onend();assert.equal(f.audio.speaking,false);f.audio.toggleVoice();assert.equal(f.settings.get('linkdid-pump-voice-muted'),'true');f.audio.speak('Third');assert.equal(f.spoken.length,2)});
test('browsers without speech support still allow the pump audio controller',()=>{const f=fixture();delete f.window.speechSynthesis;assert.equal(f.audio.hasVoice(),false);assert.doesNotThrow(()=>{f.audio.speak('Filling');f.audio.stopVoice();f.audio.toggleVoice()})});
